CREATE TABLE BorrowedBook (
    TransactionID INTEGER NOT NULL,
    ISBN VARCHAR(20) NOT NULL,
    PRIMARY KEY (TransactionID, ISBN),
    CONSTRAINT FK_Transaction FOREIGN KEY (TransactionID) REFERENCES Transaction(TransactionID) ON DELETE CASCADE, 
    CONSTRAINT FK_Book FOREIGN KEY (ISBN) REFERENCES Book(ISBN) ON DELETE CASCADE
)